//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;

#if !RS20171

////[assembly: global::System.Windows.Markup.XmlnsDefinitionAttribute("urn:shemas-jetbrains-com:ui-application-icons-xxx-themed-icons", "JetBrains.UI.ThemedIcons")]

namespace XmlDocInspections.Plugin.Settings
{
    public sealed class XmlDocInspectionsIcons
    {
        #region Xml16
        [global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsAttribute()]
        [ExcludeFromCodeCoverage]
        public sealed class Xml16 : global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsClass
        {

            /// <inheritdoc cref="Xml16">identifier class</inheritdoc>
            public static global::JetBrains.UI.Icons.IconId Id = new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsId(typeof(Xml16));

            /// <summary>Loads the image for Themed Icon Xml16 theme aspect Default.</summary>
            public global::JetBrains.Application.UI.Icons.Images.TiImage Load_Default()
            {
                return global::JetBrains.Application.UI.Icons.Images.TiImageConverter.FromCanonicalSExpressionAsciiString("(7:TiImage2:v1(6:Vector(4:Size5:16,16)(7:Drawing(4:Path(4:Fill(5:Solid9:#FFA441CC" +
                        "))(8:Segments(1:F8:5.0271079:12.9053431:11:1)(1:L8:0.3205899:10.350257)(1:L8:0.3" +
                        "205898:9.300564)(1:L8:5.0271078:6.745481)(1:L8:5.0271078:8.066628)(1:L18:1.64754" +
                        "999999999998:9.830464)(1:L8:5.02710718:11.584195999999999)(1:L8:5.0271079:12.905" +
                        "344)(1:F8:5.0271079:12.9053431:10:)))(4:Path(4:Fill(5:Solid9:#FFA441CC))(8:Segme" +
                        "nts(1:F8:9.7466358:5.7449311:11:1)(1:L18:6.88119699999999939:14.327402)(1:L18:5." +
                        "77212099999999949:14.327402)(1:L18:8.625931999999998818:5.7449309999999993)(1:L1" +
                        "8:9.746635999999998718:5.7449309999999993)(1:F8:9.7466358:5.7449311:10:)))(4:Pat" +
                        "h(4:Fill(5:Solid9:#FFA441CC))(8:Segments(1:F9:15.6859859:10.3502571:11:1)(1:L9:1" +
                        "0.70261218:12.905342999999999)(1:L9:10.70261218:11.584194999999998)(1:L9:14.0818" +
                        "9218:9.8254789999999979)(1:L9:10.70261218:8.0666269999999969)(1:L9:10.70261217:6" +
                        ".745479999999997)(1:L9:15.68598518:9.3005629999999968)(1:L9:15.68598518:10.35025" +
                        "5999999996)(1:F9:15.6859859:10.3502571:10:)))(4:Path(4:Fill(5:Solid9:#FFA441CC))" +
                        "(8:Segments(1:F18:12.67648887634277318:2.65436911582946781:11:1)(1:L18:13.366247" +
                        "17712402317:3.915287971496582)(1:L18:14.62716388702392618:4.6050453186035156)(1:" +
                        "L18:13.36624717712402318:5.2948064804077148)(1:L18:12.67648887634277318:6.555720" +
                        "8061218262)(1:L18:11.98672962188720718:5.2948064804077148)(1:L18:10.725809097290" +
                        "03918:4.6050453186035156)(1:L18:11.98672962188720717:3.915287971496582)))(4:Path" +
                        "(4:Fill(5:Solid9:#FFA441CC))(8:Segments(1:F18:9.274153709411621119:0.39119398593" +
                        "9025881:11:1)(1:L18:9.897784233093261718:1.5317199230194092)(1:L18:11.0383090972" +
                        "9003918:2.1553499698638916)(1:L18:9.897784233093261718:2.7789802551269531)(1:L18" +
                        ":9.274153709411621118:3.9195055961608887)(1:L18:8.650524139404296918:2.778980255" +
                        "1269531)(1:L18:7.510000228881835918:2.1553499698638916)(1:L18:8.6505241394042969" +
                        "18:1.5317199230194092))))(8:ClipMask)))");
            }

            /// <summary>Returns the set of theme images for Themed Icon Xml16.</summary>
            public override global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[] GetThemeImages()
            {
                return new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[] {
                new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage("Default", new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(this.Load_Default))};
            }
        }
        #endregion
    }
}
#endif
