name: build

on:
  - workflow_dispatch
  - push

env:
  BuildConfiguration: Release
  BuildVersion: 2.22.0.${{ github.run_number }}

jobs:
  build:
    name: build
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run Build.ps1
        run: >
          ./Build/Build.ps1
          -Configuration "${{ env.BuildConfiguration }}"
          -Version "${{ env.BuildVersion }}"
          -BranchName "${{ github.ref_name }}"
          -CoverageBadgeUploadToken "${{ secrets.COVERAGE_BADGE_UPLOAD_TOKEN }}"

      - name: Upload Packages artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Packages
          path: |
            Build/Output/*.nupkg
            Build/Output/*.zip

      - name: Upload TestOutput artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: TestOutput
          path: |
            Build/Output/TestResults/**
            Build/Output/TestCoverage/**
